---

- hosts: all
  become: true
  tasks:

#  - name: Update repository index
#    apt:
#      update_cache: yes
#    when: ansible_distribution == "Ubuntu"

  - name: Install Apache and Php packages for ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install Apache packages for CentOS
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
