---

- hosts: all
  become: true
  tasks:

  - name: Update repository index
    apt:
      update_cache: yes

  - name: Install Apache package
    apt:
      name: apache2
      state: absent

  - name: Add php support apache
    apt:
      name: libapache2-mod-php
      state: absent
