---

- hosts: all
  become: true
  tasks:

  - name: install updates (Centos)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:


  - name: Install Apache and Php packages for ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install Apache packages for CentOS
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks:
  - name: install mariadb package (centos)
    dnf:
      name: mariadb
      state: latest
   when: ansible_distribution == "CentOS"

  - name: install mariadb package (ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"
